# Generated by Django 3.1.5 on 2021-01-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
