# Generated by Django 3.1.5 on 2021-02-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20210130_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='display_info',
            field=models.TextField(default='', max_length=200),
        ),
    ]
