# Generated by Django 3.1.5 on 2021-04-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_u',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
