# Generated by Django 3.1.5 on 2021-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210411_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_u',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_u',
            name='message',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
