# Generated by Django 3.1.5 on 2021-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='contact_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
